services:
  nextjs-app:
    build: .
    container_name: nextjs
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    ports:
      - "3002:3000"
    command: ["npm", "run", "start"]