services:
  nextjs-app:
    build: .
    container_name: nextjs
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3004:3000'
    command: ['npm', 'run', 'start']
    labels:
      logging: 'loki'
      app: 'vietpolyglots'
      service: 'nextjs-app'
      environment: 'production'
